on:
  push:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install node v21
      uses: actions/setup-node@v4
      with:
        node-version: 21
    - name: python install
      run: python3 -m pip install setuptools
    - name: npm install
      run: npm install --build-from-source
    - name: install ts
      run: npm install typescript
    - name: tsc compile
      uses: iCrawl/action-tsc@v1
