on:
  push:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install node v22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: python install
      run: python3 -m pip install setuptools
    - name: node-gyp install
      run: npm install -g node-gyp
    - name: npm install
      run: npm ci
    - name: install ts
      run: npm install typescript
    - name: tsc compile
      uses: iCrawl/action-tsc@v1
