on:
  push:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v21
      uses: actions/setup-node@v1
      with:
        node-version: 21
    - name: npm install
      run: npm install
    - name: install ts
      run: npm install typescript
    - name: tsc compile
      uses: iCrawl/action-tsc@v1
